### ISSUE TITLE
Request to add features to the project

### ISSUE THREAD

**Issue by israelxss** [TimHanewich/scout#2]
The code looks awesome and so does the idea
I would be very happy if you could continue the project and add GPS to maintain stability and fly according to points
and automatic landing if there is a malfunction (loss of communication)
In addition, I would recommend working with a more serious gyro like bno055

**Comment by TimHanewich** [comment]
Excellent ideas, @israelxss thanks for the suggestions. I plan to expand Scout as my time permits. A lot of these take serious R&D time. Stay tuned for updates in 2024. And thanks for the suggestion of the BNO055, I was not aware of that. Looks promising.
