### ISSUE TITLE
Python 3 instead of MicroPython

### ISSUE THREAD

**Issue by FeintEars** [TimHanewich/scout#3]
Hi

Thank you for your work!

Is there a chance to launch it on usual python 3 (for bigger raspberry pi 3 or 4)?

**Comment by israelxss** [comment]
@FeintEars pico pi is a controller and not a computer

**Comment by FeintEars** [comment]
@israelxss do you mean there are some problems for computer to handle it the same way?

**Comment by TimHanewich** [comment]
HI @FeintEars , yes, as @israelxss  mentioned, the Raspberry Pi Pico is a microcontroller, not a micro-computer like the traditional Raspberry Pi's.

The pico runs MicroPython while the traditional Pi's like the Pi 3/4 run Python ("full" Python) along with a full OS and everything. 

So no, the code for Scout supplied here in this repo would not run natively on a Pi 3/4 in Python. It would have to be ported over. In theory, it could work, just would need to make some changes to specific pieces of code that use platform-dependent libraries. 

You (or anyone) is welcome to fork this and work on that!
